// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv4E32fGZlLWApJxJLM7vCR_DLMyHcqq0',
    appId: '1:670737723186:web:5949b3843790ed9e67b12b',
    messagingSenderId: '670737723186',
    projectId: 'koozat',
    authDomain: 'koozat.firebaseapp.com',
    storageBucket: 'koozat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkdZPAawIBestDVXeNQQg1zVVWS5Taw84',
    appId: '1:670737723186:android:056da63b4190eed067b12b',
    messagingSenderId: '670737723186',
    projectId: 'koozat',
    storageBucket: 'koozat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA6VWNGM4tNg2-85_cqmZfc52_I2SE8Z0',
    appId: '1:670737723186:ios:1310d8e5900de19e67b12b',
    messagingSenderId: '670737723186',
    projectId: 'koozat',
    storageBucket: 'koozat.firebasestorage.app',
    iosBundleId: 'uz.app.koozat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA6VWNGM4tNg2-85_cqmZfc52_I2SE8Z0',
    appId: '1:670737723186:ios:1310d8e5900de19e67b12b',
    messagingSenderId: '670737723186',
    projectId: 'koozat',
    storageBucket: 'koozat.firebasestorage.app',
    iosBundleId: 'uz.app.koozat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv4E32fGZlLWApJxJLM7vCR_DLMyHcqq0',
    appId: '1:670737723186:web:ca4d8b70b95e1a5967b12b',
    messagingSenderId: '670737723186',
    projectId: 'koozat',
    authDomain: 'koozat.firebaseapp.com',
    storageBucket: 'koozat.firebasestorage.app',
  );
}
